let element2 = [
  {
    id: 0,
    saved: false,
    Overview: "This flight offers a unique experience with comfort and convenience.",
    included: "Meals, in-flight entertainment, and baggage handling are included.",
    Additional: "Wi-Fi is available on board for an extra fee.",
    img: ["https://picsum.photos/id/1015/200/150", "https://picsum.photos/id/1019/200/150", "https://picsum.photos/id/1018/200/150", "https://picsum.photos/id/1016/200/150"],
    type: "Cultural",
    companyname: "Pharaoh Travels",
    destination: "Luxor",
    rate: 50
  },
  {
    id: 1,
    saved: false,
    Overview: "This flight offers a unique experience with comfort and convenience.",
    included: "Meals, in-flight entertainment, and baggage handling are included.",
    Additional: "Wi-Fi is available on board for an extra fee.",
    img: ["https://picsum.photos/id/1015/200/150", "https://picsum.photos/id/1016/200/150", "https://picsum.photos/id/1015/200/150", "https://picsum.photos/id/1020/200/150"],
    type: "Cultural",
    companyname: "Nile Wonders Tours",
    destination: "Aswan",
    rate: 20
  },
  {
    id: 2,
    saved: false,
    Overview: "This flight offers a unique experience with comfort and convenience.",
    included: "Meals, in-flight entertainment, and baggage handling are included.",
    Additional: "Wi-Fi is available on board for an extra fee.",
    img: ["https://picsum.photos/id/1015/200/150", "https://picsum.photos/id/1016/200/150", "https://picsum.photos/id/1018/200/150", "https://picsum.photos/id/1019/200/150"],
    type: "Cultural",
    companyname: "Egypt Discovery",
    destination: "Giza",
    rate: 0
  },
  {
    id: 3,
    saved: false,
    Overview: "This flight offers a unique experience with comfort and convenience.",
    included: "Meals, in-flight entertainment, and baggage handling are included.",
    Additional: "Wi-Fi is available on board for an extra fee.",
    img: ["https://picsum.photos/id/1015/200/150", "https://picsum.photos/id/1016/200/150", "https://picsum.photos/id/1018/200/150", "https://picsum.photos/id/1019/200/150"],
    type: "Beach",
    companyname: "Red Sea Adventures",
    destination: "Hurghada",
    rate: 0
  },
  {
    id: 4,
    saved: false,
    Overview: "This flight offers a unique experience with comfort and convenience.",
    included: "Meals, in-flight entertainment, and baggage handling are included.",
    Additional: "Wi-Fi is available on board for an extra fee.",
    img: ["https://picsum.photos/id/1015/200/150", "https://picsum.photos/id/1016/200/150", "https://picsum.photos/id/1018/200/150", "https://picsum.photos/id/1019/200/150"],
    type: "Beach",
    companyname: "Blue Sky Egypt",
    destination: "Sharm El-Sheikh",
    rate: 0
  },
  {
    id: 5,
    saved: false,
    Overview: "This flight offers a unique experience with comfort and convenience.",
    included: "Meals, in-flight entertainment, and baggage handling are included.",
    Additional: "Wi-Fi is available on board for an extra fee.",
    img: ["https://picsum.photos/id/1015/200/150", "https://picsum.photos/id/1016/200/150", "https://picsum.photos/id/1018/200/150", "https://picsum.photos/id/1019/200/150"],
    type: "Beach",
    companyname: "Sun & Sea Tours",
    destination: "Marsa Alam",
    rate: 0
  },
  {
    id: 6,
    saved: false,
    Overview: "This flight offers a unique experience with comfort and convenience.",
    included: "Meals, in-flight entertainment, and baggage handling are included.",
    Additional: "Wi-Fi is available on board for an extra fee.",
    img: ["https://picsum.photos/id/1015/200/150", "https://picsum.photos/id/1016/200/150", "https://picsum.photos/id/1018/200/150", "https://picsum.photos/id/1019/200/150"],
    type: "Desert",
    companyname: "Safari Egypt",
    destination: "Siwa Oasis",
    rate: 0
  },
  {
    id: 7,
    saved: false,
    Overview: "This flight offers a unique experience with comfort and convenience.",
    included: "Meals, in-flight entertainment, and baggage handling are included.",
    Additional: "Wi-Fi is available on board for an extra fee.",
    img: ["https://picsum.photos/id/1015/200/150", "https://picsum.photos/id/1016/200/150", "https://picsum.photos/id/1018/200/150", "https://picsum.photos/id/1019/200/150"],
    type: "Desert",
    companyname: "Adventure Sinai",
    destination: "White Desert",
    rate: 0
  },
  {
    id: 8,
    saved: false,
    Overview: "This flight offers a unique experience with comfort and convenience.",
    included: "Meals, in-flight entertainment, and baggage handling are included.",
    Additional: "Wi-Fi is available on board for an extra fee.",
    img: ["https://picsum.photos/id/1015/200/150", "https://picsum.photos/id/1016/200/150", "https://picsum.photos/id/1018/200/150", "https://picsum.photos/id/1019/200/150"],
    type: "Desert",
    companyname: "Nomad Trek",
    destination: "Bahariya Oasis",
    rate: 0
  },
  {
    id: 9,
    saved: false,
    Overview: "This flight offers a unique experience with comfort and convenience.",
    included: "Meals, in-flight entertainment, and baggage handling are included.",
    Additional: "Wi-Fi is available on board for an extra fee.",
    img: ["https://picsum.photos/id/1015/200/150", "https://picsum.photos/id/1016/200/150", "https://picsum.photos/id/1018/200/150", "https://picsum.photos/id/1019/200/150"],
    type: "Religious",
    companyname: "Spiritual Egypt",
    destination: "Saint Catherine",
    rate: 0
  },
  {
    id: 10,
    saved: false,
    Overview: "This flight offers a unique experience with comfort and convenience.",
    included: "Meals, in-flight entertainment, and baggage handling are included.",
    Additional: "Wi-Fi is available on board for an extra fee.",
    img: ["https://picsum.photos/id/1015/200/150", "https://picsum.photos/id/1016/200/150", "https://picsum.photos/id/1018/200/150", "https://picsum.photos/id/1019/200/150"],
    type: "Religious",
    companyname: "Faith Tours Egypt",
    destination: "Al-Azhar Mosque",
    rate: 0
  },
  {
    id: 11,
    saved: false,
    Overview: "This flight offers a unique experience with comfort and convenience.",
    included: "Meals, in-flight entertainment, and baggage handling are included.",
    Additional: "Wi-Fi is available on board for an extra fee.",
    img: ["https://picsum.photos/id/1015/200/150", "https://picsum.photos/id/1016/200/150", "https://picsum.photos/id/1018/200/150", "https://picsum.photos/id/1019/200/150"],
    type: "Religious",
    companyname: "Holy Sites Egypt",
    destination: "Hanging Church",
    rate: 0
  },
  {
    id: 12,
    saved: false,
    Overview: "This flight offers a unique experience with comfort and convenience.",
    included: "Meals, in-flight entertainment, and baggage handling are included.",
    Additional: "Wi-Fi is available on board for an extra fee.",
    img: ["https://picsum.photos/id/1015/200/150", "https://picsum.photos/id/1016/200/150", "https://picsum.photos/id/1018/200/150", "https://picsum.photos/id/1019/200/150"],
    type: "Shopping",
    companyname: "Cairo Bazaars",
    destination: "Khan El-Khalili",
    rate: 0
  },
  {
    id: 13,
    saved: false,
    Overview: "This flight offers a unique experience with comfort and convenience.",
    included: "Meals, in-flight entertainment, and baggage handling are included.",
    Additional: "Wi-Fi is available on board for an extra fee.",
    img: ["https://picsum.photos/id/1015/200/150", "https://picsum.photos/id/1016/200/150", "https://picsum.photos/id/1018/200/150", "https://picsum.photos/id/1019/200/150"],
    type: "Shopping",
    companyname: "Luxury Nile Tours",
    destination: "City Stars Mall",
    rate: 0
  },
  {
    id: 14,
    saved: false,
    Overview: "This flight offers a unique experience with comfort and convenience.",
    included: "Meals, in-flight entertainment, and baggage handling are included.",
    Additional: "Wi-Fi is available on board for an extra fee.",
    img: ["https://picsum.photos/id/1015/200/150", "https://picsum.photos/id/1016/200/150", "https://picsum.photos/id/1018/200/150", "https://picsum.photos/id/1019/200/150"],
    type: "Shopping",
    companyname: "Modern Egypt Tours",
    destination: "Mall of Egypt",
    rate: 0
  },
  {
    id: 15,
    saved: false,
    Overview: "This flight offers a unique experience with comfort and convenience.",
    included: "Meals, in-flight entertainment, and baggage handling are included.",
    Additional: "Wi-Fi is available on board for an extra fee.",
    img: ["https://picsum.photos/id/1015/200/150", "https://picsum.photos/id/1016/200/150", "https://picsum.photos/id/1018/200/150", "https://picsum.photos/id/1019/200/150"],
    type: "Medical",
    companyname: "MedCare Egypt",
    destination: "6th of October City",
    rate: 0
  },
  {
    id: 16,
    saved: true,
    img: ["/The beauty of Egyptian nature 🇪🇬 📍Wadi Elweshwash Nuweiba Egypt Sinai.jpeg"],
    type: "Medical",
    companyname: "Nuweiba Healing Tours",
    destination: "Wadi El-Weshwash",
    rate: 19
  },
  {
    id: 17,
    saved: false,
    Overview: "This flight offers a unique experience with comfort and convenience.",
    included: "Meals, in-flight entertainment, and baggage handling are included.",
    Additional: "Wi-Fi is available on board for an extra fee.",
    img: ["/The beauty of Egyptian nature 🇪🇬 📍Wadi Elweshwash Nuweiba Egypt Sinai.jpeg"],
    type: "Medical",
    companyname: "Sinai Wellness Trips",
    destination: "Nuweiba",
    rate: 0
  }
];

export { element2 };
